stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_REGISTRY: registry.gitlab.com/cyclops4100006/datadiscovery

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"


build_modules:
  stage: build
  script:
    - docker compose -f docker-compose-ci.yml build --no-cache
    - docker push $IMAGE_REGISTRY/profile_prepro
    - docker push $IMAGE_REGISTRY/modelling
  tags:
    - docker
  only:
    - main
    - cyclops-integration

#deploy_profile_prepro:
#  stage: deploy
#  script:
#    - echo "Running profile_prepro module"
#    - docker compose -f docker-compose-ci.yml pull profile_prepro
#    - docker compose -f docker-compose-ci.yml run --rm -e MINIO_ENDPOINT=http://minio:9000 -e MINIO_ACCESS_KEY=minioadmin -e MINIO_SECRET_KEY=minioadmin123 -e MINIO_BUCKET=data-based-data-discovery -e MINIO_FOLDER_BENCHMARK=datalake profile_prepro
#    - docker ps
#  tags:
#    - docker
#  only:
#    - main
#    - cyclops-integration
#  needs:
#    - build_modules


deploy_modelling:
  stage: deploy
  script:
    - echo "Deploying modelling module"
    - docker compose -f docker-compose-ci.yml pull modelling
    - docker compose -f docker-compose-ci.yml up -e MINIO_ENDPOINT=http://minio:9000 -e MINIO_ACCESS_KEY=minioadmin -e MINIO_SECRET_KEY=minioadmin123 -e MINIO_BUCKET=data-based-data-discovery -d modelling
    - docker ps
  tags:
    - docker
  only:
    - main
    - cyclops-integration
  needs:
    - build_modules #- deploy_profile_prepro
