services:
  profile_prepro:
    build:
      context: ./profile_prepro
    container_name: profile_prepro
    environment:
      MINIO_ENDPOINT: http://minio:9200
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: data-based-data-discovery
    networks:
      - shared_net
    entrypoint: ["/app/profile_pipeline_minio.sh"]

  modelling:
    build:
      context: ./modelling
    container_name: ranking_model
    environment:
      MINIO_ENDPOINT: http://minio:9200
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: data-based-data-discovery
    networks:
      - shared_net
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
        - "8000:8000"

networks:
  shared_net:
    external: true
    name: long-term-storage_default
